import type { NextPage } from 'next'
import { useContext } from 'react';
import Layout from '../src/components/Layout'
import AppContext from '../src/store/AppContext';
import { AppProvider } from "../src/store/AppContext"
import BestProducts from "../src/components/home/BestProducts"

const Home: NextPage = (props) => {

  return (
    <AppProvider>
    <Layout categories={props.categories}>
      <BestProducts />
    </Layout>
    </AppProvider>
  )
}

export default Home

import client from "../src/client/ApolloClient"
import { GetStaticProps, GetStaticPaths, GetServerSideProps } from 'next'
import CATEGORIES_QUERY from "../src/queries/categories-and-subcategories"

export const getStaticProps: GetStaticProps = async (context) => {
  //TODO: Ici, on va faire en sorte de transformer nos données récupérés

  const { data } = await client.query({
    query: CATEGORIES_QUERY,
  })

  let categories = data?.productCategories?.nodes
        ? data.productCategories.nodes
        : []

  let result = {
    props: { 
      categories: categories
    },
    revalidate: 1,
  }

  return result
}

/* 
<div className={styles.container}>
      <Head>
        <title>Wild fashion Universe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
*/